const formations = [
  {letter: 'A', name: 'Caterpillar'},
  {letter: 'B', name: 'Stairstep'},
  {letter: 'C', name: 'Hour Glass'},
  {letter: 'D', name: 'Hope Diamond'},
  {letter: 'E', name: 'Rubick'},
  {letter: 'F', name: 'Diamond Flake'},
  {letter: 'G', name: 'Arrowhead'},
  {letter: 'H', name: 'Iriquois'},
  {letter: 'J', name: 'Springbok'},
  {letter: 'K', name: 'Crossbow'},
  {letter: 'K', name: 'Crank'},
  // {letter: 'L', name: 'Openfaceingdiamond'},
  {letter: 'L', name: 'Open Diamond'},
  {letter: 'M', name: 'Double Spiders'},
  // {letter: 'M', name: 'Spider'},
  {letter: 'N', name: 'Zipperflake'},
  {letter: 'O', name: 'Compressed Accordion'},
  {letter: 'P', name: 'Venus'},
  {letter: 'Q', name: 'Compass'},
  // {letter: '1', name: 'donutflakedonutflake'},
  // {letter: '2', name: 'swissbearsswissbears'},
  // {letter: '3', name: 'doublechineseteesdoubledonuts'},
  // {letter: '4', name: 'snowflakeinout'},
  // {letter: '4', name: 'snowflakeoffset'},
  // {letter: '5', name: 'crankcrank'},
  // {letter: '5', name: 'waggawagga'},
  // {letter: '6', name: 'starstar'},
  // {letter: '7', name: 'nachonacho'},
  // {letter: '7', name: 'bipoledonutsbipoledonuts'},
  // {letter: '8', name: 'frisbeefrisbee'},
  // // {letter: '9', name: 'tajmahal'},
  // // {letter: '10', name: 'donutdonut'},
  // // {letter: '11', name: 'norwegianboxnorwegiandonut'},
  // // {letter: '12', name: 'stereobipolestereobipole'},
  // {letter: '13', name: 'doublesatellitedoublesatellite'},
  // {letter: '13', name: 'satellitesatellite'},
  // {letter: '14', name: 'accordianopposedstairsteps'},
  // {letter: '14', name: 'openaccordianopposedstairsteps'},
  // // {letter: '15', name: 'opalzipperzipperopal'},
  // {letter: '16', name: 'canadianteesmonopods'},
  // {letter: '17', name: 'buzzardbuzzard'},
  // {letter: '18', name: 'sidebodydonutsidebodydonuts'},
  // {letter: '19', name: 'compresseddiamondscompresseddiamonds'},
  // {letter: '19', name: 'compdiamondscompdiamonds'},
  // // {letter: '20', name: 'compresseddiamondscompresseddiamonds'},
  // // {letter: '20', name: 'catdiamondscatacordion'},
  // {letter: '21', name: 'stereopodstereopod'},
  // {letter: '21', name: 'legoeye'},
  // {letter: '22', name: 'oldbonecompdiamonds'},
];

module.exports = formations
