const formations = [
  {letter: 'A', name: 'Caterpillar', image:'resources/a-caterpillar.png'},
  {letter: 'B', name: 'Stairstep', image:'resources/b-Stairstep.png'},
  {letter: 'C', name: 'Hour Glass', image:'resources/c-hourglass.png'},
  {letter: 'D', name: 'Hope Diamond', image:'resources/d-hopediamond.png'},
  {letter: 'E', name: 'Rubick', image:'resources/e-rubick.png'},
  {letter: 'F', name: 'Diamond Flake', image:'resources/f-diamondflake.png'},
  {letter: 'G', name: 'Arrowhead', image:'resources/g-arrowhead.png'},
  {letter: 'H', name: 'Iriquois', image:'resources/h-iriquois.png'},
  {letter: 'J', name: 'Springbok', image:'resources/j-springbok.png'},
  {letter: 'K', name: 'Crossbow', image:'resources/k-crossbow.png'},
  // {letter: 'K', name: 'Crank', image:'resources/K-Crank.png'},
  // {letter: 'L', name: 'Openfaceingdiamond', image:'resources/L-Openfaceingdiamond.png'},
  {letter: 'L', name: 'Open Diamond', image:'resources/l-openfacedimond.png'},
  {letter: 'M', name: 'Double Spiders', image:'resources/m-doublespiders.png'},
  // {letter: 'M', name: 'Spider', image:'resources/M-Spider.png'},
  {letter: 'N', name: 'Zipperflake', image:'resources/n-zipperflake.png'},
  {letter: 'O', name: 'Compressed Accordion', image:'resources/o-compressedaccordian.png'},
  {letter: 'P', name: 'Venus', image:'resources/p-venus.png'},
  {letter: 'Q', name: 'Compass', image:'resources/q-compass.png'},
  // {letter: '1', name: 'donutflakedonutflake'},
  // {letter: '2', name: 'swissbearsswissbears'},
  // {letter: '3', name: 'doublechineseteesdoubledonuts'},
  // {letter: '4', name: 'snowflakeinout'},
  // {letter: '4', name: 'snowflakeoffset'},
  // {letter: '5', name: 'crankcrank'},
  // {letter: '5', name: 'waggawagga'},
  // {letter: '6', name: 'starstar'},
  // {letter: '7', name: 'nachonacho'},
  // {letter: '7', name: 'bipoledonutsbipoledonuts'},
  // {letter: '8', name: 'frisbeefrisbee'},
  // // {letter: '9', name: 'tajmahal'},
  // // {letter: '10', name: 'donutdonut'},
  // // {letter: '11', name: 'norwegianboxnorwegiandonut'},
  // // {letter: '12', name: 'stereobipolestereobipole'},
  // {letter: '13', name: 'doublesatellitedoublesatellite'},
  // {letter: '13', name: 'satellitesatellite'},
  // {letter: '14', name: 'accordianopposedstairsteps'},
  // {letter: '14', name: 'openaccordianopposedstairsteps'},
  // // {letter: '15', name: 'opalzipperzipperopal'},
  // {letter: '16', name: 'canadianteesmonopods'},
  // {letter: '17', name: 'buzzardbuzzard'},
  // {letter: '18', name: 'sidebodydonutsidebodydonuts'},
  // {letter: '19', name: 'compresseddiamondscompresseddiamonds'},
  // {letter: '19', name: 'compdiamondscompdiamonds'},
  // // {letter: '20', name: 'compresseddiamondscompresseddiamonds'},
  // // {letter: '20', name: 'catdiamondscatacordion'},
  // {letter: '21', name: 'stereopodstereopod'},
  // {letter: '21', name: 'legoeye'},
  // {letter: '22', name: 'oldbonecompdiamonds'},
];

module.exports = formations
